name: main
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: dalance/qemu@v2
      with:
        version: '6.0'
    - name: Download Windows ISO
      run: |
        Invoke-WebRequest -Uri "https://software-download.microsoft.com/download/pr/22000.258.210806-1427.co_release_CLIENT_CONSUMER_x64FRE_en-us.iso" -OutFile "Windows.iso"
    - name: Create disk image
      run: qemu-img create -f qcow2 windows.qcow2 40G
    - name: Run QEMU
      run: qemu-system-x86_64 -m 4096 -boot d -drive file=windows.qcow2,format=qcow2 -cdrom Windows.iso -display sdl -vga std -accel hax
